name: Lint

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: ".nvmrc"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
